import MapMaker from "./MapMaker"
export default function(){
  const data = MapMaker()
  return { "height":150,
  "infinite":false,
  "layers":[
         {
          "data": data,
          "height":150,
          "id":1,
          "name":"Tile Layer 1",
          "opacity":1,
          "type":"tilelayer",
          "visible":true,
          "width":300,
          "x":0,
          "y":0
         }],
  "nextlayerid":2,
  "nextobjectid":1,
  "orientation":"orthogonal",
  "renderorder":"right-down",
  "tiledversion":"1.2.3",
  "tileheight":32,
  "tilesets":[
         {
          "columns":6,
          "firstgid":1,
          "image":"DesertTiles.png",
          "imageheight":160,
          "imagewidth":192,
          "margin":0,
          "name":"DesertTiles",
          "spacing":0,
          "tilecount":30,
          "tileheight":32,
          "tiles":[
                 {
                  "id":0,
                  "properties":[
                         {
                          "name":"Collides",
                          "type":"bool",
                          "value":true
                         }]
                 },
                 {
                  "id":1,
                  "properties":[
                         {
                          "name":"Collides",
                          "type":"bool",
                          "value":true
                         }]
                 },
                 {
                  "id":2,
                  "properties":[
                         {
                          "name":"Collides",
                          "type":"bool",
                          "value":true
                         }]
                 },
                 {
                  "id":3,
                  "properties":[
                         {
                          "name":"Collides",
                          "type":"bool",
                          "value":true
                         }]
                 },
                 {
                  "id":4,
                  "properties":[
                         {
                          "name":"Collides",
                          "type":"bool",
                          "value":true
                         }]
                 },
                 {
                  "id":5,
                  "properties":[
                         {
                          "name":"Collides",
                          "type":"bool",
                          "value":true
                         }]
                 },
                 {
                  "id":6,
                  "properties":[
                         {
                          "name":"Collides",
                          "type":"bool",
                          "value":true
                         }]
                 },
                 {
                  "id":7,
                  "properties":[
                         {
                          "name":"Collides",
                          "type":"bool",
                          "value":true
                         }]
                 },
                 {
                  "id":8,
                  "properties":[
                         {
                          "name":"Collides",
                          "type":"bool",
                          "value":true
                         }]
                 }],
          "tilewidth":32
         }],
  "tilewidth":32,
  "type":"map",
  "version":1.2,
  "width":300
 }

}
