import MapMaker from "./MapMaker"
export default function(){
  const data = MapMaker()
  return { "height":600,
  "infinite":false,
  "layers":[
         {
          "data":data,
          "height":600,
          "id":1,
          "name":"Tile Layer 1",
          "opacity":1,
          "type":"tilelayer",
          "visible":true,
          "width":600,
          "x":0,
          "y":0
         }],
  "nextlayerid":2,
  "nextobjectid":1,
  "orientation":"orthogonal",
  "renderorder":"right-down",
  "tiledversion":"1.2.3",
  "tileheight":32,
  "tilesets":[
         {
          "columns":6,
          "firstgid":1,
          "image":"DesertTiles.png",
          "imageheight":160,
          "imagewidth":192,
          "margin":0,
          "name":"world",
          "spacing":0,
          "terrains":[
                 {
                  "name":"New Terrain",
                  "tile":3
                 }],
          "tilecount":27,
          "tileheight":32,
          "tiles":[
                 {
                  "id":1,
                  "properties":[
                         {
                          "name":"Collides",
                          "type":"bool",
                          "value":true
                         }]
                 },
                 {
                  "id":2,
                  "properties":[
                         {
                          "name":"Collides",
                          "type":"bool",
                          "value":true
                         }]
                 },
                 {
                  "id":3,
                  "objectgroup":
                     {
                      "draworder":"index",
                      "name":"",
                      "objects":[
                             {
                              "height":5.81818181818182,
                              "id":1,
                              "name":"",
                              "rotation":0,
                              "type":"",
                              "visible":true,
                              "width":32.9090909090909,
                              "x":-0.545454545454546,
                              "y":0
                             }],
                      "opacity":1,
                      "type":"objectgroup",
                      "visible":true,
                      "x":0,
                      "y":0
                     },
                  "properties":[
                         {
                          "name":"Collides",
                          "type":"bool",
                          "value":true
                         }]
                 },
                 {
                  "id":4,
                  "properties":[
                         {
                          "name":"Collides",
                          "type":"bool",
                          "value":true
                         }]
                 },
                 {
                  "id":5,
                  "properties":[
                         {
                          "name":"Collides",
                          "type":"bool",
                          "value":true
                         }]
                 },
                 {
                  "id":6,
                  "properties":[
                         {
                          "name":"Collides",
                          "type":"bool",
                          "value":true
                         }]
                 },
                 {
                  "id":7,
                  "properties":[
                         {
                          "name":"Collides",
                          "type":"bool",
                          "value":true
                         }]
                 }],
          "tilewidth":32,
          "transparentcolor":"#ff00ff"
         }],
  "tilewidth":32,
  "type":"map",
  "version":1.2,
  "width":600
 }
}
