import MapMaker from "./MapMaker"
export default function(type:string){
  const data = MapMaker(type)
  return { "height":100,
  "infinite":false,
  "layers":[
         {
          "data": data,
          "height":100,
          "id":1,
          "name":"Tile Layer 1",
          "opacity":1,
          "type":"tilelayer",
          "visible":true,
          "width":150,
          "x":0,
          "y":0
         }],
  "nextlayerid":2,
  "nextobjectid":1,
  "orientation":"orthogonal",
  "renderorder":"right-down",
  "tiledversion":"1.2.3",
  "tileheight":32,
  "tilesets":[
         {
          "columns":6,
          "firstgid":1,
          "image":`${type}`,
          "imageheight":160,
          "imagewidth":192,
          "margin":0,
          "name":type,
          "spacing":0,
          "tilecount":30,
          "tileheight":32,
          "tiles":[
                 {
                  "id":0,
                  "properties":[
                         {
                          "name":"Collides",
                          "type":"bool",
                          "value":true
                         }]
                 },
                 {
                  "id":1,
                  "properties":[
                         {
                          "name":"Collides",
                          "type":"bool",
                          "value":true
                         }]
                 },
                 {
                  "id":2,
                  "properties":[
                         {
                          "name":"Collides",
                          "type":"bool",
                          "value":true
                         }]
                 },
                 {
                  "id":3,
                  "properties":[
                         {
                          "name":"Collides",
                          "type":"bool",
                          "value":true
                         }]
                 },
                 {
                  "id":4,
                  "properties":[
                         {
                          "name":"Collides",
                          "type":"bool",
                          "value":true
                         }]
                 },
                 {
                  "id":5,
                  "properties":[
                         {
                          "name":"Collides",
                          "type":"bool",
                          "value":true
                         }]
                 },
                 {
                  "id":6,
                  "properties":[
                         {
                          "name":"Collides",
                          "type":"bool",
                          "value":true
                         }]
                 },
                 {
                  "id":7,
                  "properties":[
                         {
                          "name":"Collides",
                          "type":"bool",
                          "value":true
                         }]
                 },
                 {
                  "id":8,
                  "properties":[
                         {
                          "name":"Collides",
                          "type":"bool",
                          "value":true
                         }]
                 }],
          "tilewidth":32
         }],
  "tilewidth":32,
  "type":"map",
  "version":1.2,
  "width":150
 }

}
